language: python

python:
  - "3.6"
  - "3.5"

services: redis

install:
  - "pip install ."
  - "pip install -r test_app/requirements"

script:
  - cd test_app/demo
  - python manage.py migrate
  - coverage run --source='.' manage.py test

after_success: coveralls
